/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include "android_log_print.h"
/* Header for class com_yzd_android_mcs_phone_utils_NdkUtils */

#ifndef _Included_com_yzd_android_mcs_phone_utils_NdkUtils
#define _Included_com_yzd_android_mcs_phone_utils_NdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yzd_android_mcs_phone_utils_NdkUtils
 * Method:    ndkTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jintArray JNICALL Java_com_yzd_android_mcs_1phone_utils_NdkUtils_auchCRCLo(JNIEnv *, jobject);
JNIEXPORT jintArray JNICALL Java_com_yzd_android_mcs_1phone_utils_NdkUtils_auchCRCHi(JNIEnv *, jobject);
JNIEXPORT jstring   JNICALL Java_com_yzd_android_mcs_1phone_utils_NdkUtils_getCrc16(JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
